FROM centos:7

ENV MYSQL_REPO="https://dev.mysql.com/get/mysql57-community-release-el7-10.noarch.rpm"
RUN rpm -ivh ${MYSQL_REPO}

RUN yum install epel-release sudo vim fping telnet wget configure net-tools gcc make zlib-devel libffi-devel libxml2-devel net-snmp-devel libcurl-devel openssl openssl-devel crontabs libevent-devel mysql-devel mysql-community-client logrotate -y
RUN yum groupinstall 'Development Tools' -y

RUN yum install https://dl.grafana.com/oss/release/grafana-5.4.2-1.x86_64.rpm -y
RUN wget https://dl.grafana.com/oss/release/grafana-5.4.2-1.x86_64.rpm
RUN yum install initscripts urw-fonts -y
RUN yum install grafana -y

