#!/bin/bash
TIMEOUT=$1
HOST=$2
PORT=$3

if [ -z "$PORT" ]; then
    PORT=443;
else
    PORT=$PORT;
fi

DOMAIN=$(echo ${HOST#ssl_*})

ORIGINAL_DATE=$(timeout $TIMEOUT openssl s_client -connect ${DOMAIN}:${PORT} 2>/dev/null | openssl x509 -noout -dates 2>/dev/null | grep notAfter | cut -d'=' -f2)

if [ -n "$ORIGINAL_DATE" ]; then
    EXPIRE_IN_SECS=$(date -d "${ORIGINAL_DATE}" +%s)
    EXPIRE_TIME=$(( ${EXPIRE_IN_SECS} - `date +%s` ))
    if test $EXPIRE_TIME -lt 0; then
        RETVAL=0
    else
        RETVAL=$(( ${EXPIRE_TIME} / 24 / 3600 ))
    fi
    echo ${RETVAL}
else
    echo 0
fi